[tool.poetry]
name = "fastapi-crud-mongodb"
version = "0.1.0"
description = ""
authors = ["Ï€ <pirayan20@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.112.2"
uvicorn = "^0.30.6"
pymongo = "^4.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
